### ISSUE TITLE
[Pagination]开始pageSizeSelector提示Failed prop type: Invalid prop `focusedKey` of type `number` supplied to `Config(Menu)`, expected `string`.

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#3817]
### Component 
Pagination
### Feature Description
代码
- 版本v1.25.27
```
   <Pagination
          pageSizeSelector="dropdown"
      />
```
提示
```
react.development.js:220 Warning: Failed prop type: Invalid prop `focusedKey` of type `number` supplied to `Config(Menu)`, expected `string`.
    at ConfigedComponent2 (http://localhost:3335/node_modules/.vite/@alifd_next.js?v=6323b302:8631:42)
    at Select2 (http://localhost:3335/node_modules/.vite/@alifd_next.js?v=6323b302:19029:41)
    at ConfigedComponent2 (http://localhost:3335/node_modules/.vite/@alifd_next.js?v=6323b302:8631:42)
    at div
    at div
    at Pagination2 (http://localhost:3335/node_modules/.vite/@alifd_next.js?v=6323b302:31724:42)
    at ConfigedComponent2 (http://localhost:3335/node_modules/.vite/@alifd_next.js?v=6323b302:8631:42)
    at div
    at ResponsiveGrid2 (http://localhost:3335/node_modules/.vite/@alifd_next.js?v=6323b302:28366:42)
    at ConfigedComponent2 (http://localhost:3335/node_modules/.vite/@alifd_next.js?v=6323b302:8631:42)
    at Dashboard
    at PagePropsWrapper
    at ClientWrapper (http://localhost:3335/.ice/plugins/react-app/pluginRuntime/runtime.tsx:160:31)
    at ErrorBoundaryWrapper
    at AuthWrappedComponent (http://localhost:3335/.ice/plugins/auth/pluginRuntime/runtime.tsx:9:20)
    at Suspense
    at Route2 (http://localhost:3335/node_modules/.vite/react-router-dom.js?v=6323b302:478:29)
    at Switch2 (http://localhost:3335/node_modules/.vite/react-router-dom.js?v=6323b302:622:29)
    at Routes (http://localhost:3335/.ice/plugins/router/pluginRuntime/runtime/Router.tsx:123:3)
    at div
    at default (http://localhost:3335/src/layouts/BasicLayout/index.tsx?t=1647601266127:17:3)
    at Route2 (http://localhost:3335/node_modules/.vite/react-router-dom.js?v=6323b302:478:29)
    at Switch2 (http://localhost:3335/node_modules/.vite/react-router-dom.js?v=6323b302:622:29)
    at Routes (http://localhost:3335/.ice/plugins/router/pluginRuntime/runtime/Router.tsx:123:3)
    at Router2 (http://localhost:3335/node_modules/.vite/react-router-dom.js?v=6323b302:201:30)
    at IceRouter (http://localhost:3335/.ice/plugins/router/pluginRuntime/runtime/Router.tsx:86:5)
    at Provider (http://localhost:3335/.ice/plugins/auth/pluginRuntime/runtime/Auth.tsx:6:3)
    at AuthStoreProvider (http://localhost:3335/.ice/plugins/auth/pluginRuntime/runtime.tsx:56:5)
    at App
```

**Comment by angentle** [comment]
也遇到同样的问题。
Warning: Failed prop type: Invalid prop `focusedKey` of type `number` supplied to `Config(Menu)`, expected `string`.

react_devtools_backend.js:3973 Warning: Failed prop type: Invalid prop `focusedKey` of type `array` supplied to `Config(Menu)`, expected `string`.

Warning: Failed prop type: Invalid prop `focusedKey` of type `array` supplied to `Menu`, expected `string`.

**Comment by weinianyang** [comment]
设置dropdown的时候，会渲染一个Select，这个Select的highlightKey会变成number，然后Select里面的Menu接收了这个highlightKey作为他的focusedKey，Menu的focusedKey的类型是string的
