### ISSUE TITLE
[Table]开启useVirtual，使用immer会报错"Cannot assign to read only property '__rowIndex' of object '#<Object>'"

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4379]
### Component 
Table
### Feature Description
DEMO： https://codepen.io/xmsz/pen/rNQyjRg?editors=0011

```
lib??react/17.0.2/umd/react.production.min.js,react-dom/17.0.2/umd/react-dom.production.min.js,prop-types/15.8.1/prop-types.js:172 TypeError: Cannot assign to read only property '__rowIndex' of object '#<Object>'
    at next.min.js:20:252878
    at Array.forEach (<anonymous>)
    at n.render (next.min.js:20:252790)
    at Te (lib??react/17.0.2/umd/react.production.min.js,react-dom/17.0.2/umd/react-dom.production.min.js,prop-types/15.8.1/prop-types.js:150:308)
    at Ch (lib??react/17.0.2/umd/react.production.min.js,react-dom/17.0.2/umd/react-dom.production.min.js,prop-types/15.8.1/prop-types.js:150:105)
    at Pj (lib??react/17.0.2/umd/react.production.min.js,react-dom/17.0.2/umd/react-dom.production.min.js,prop-types/15.8.1/prop-types.js:264:139)
    at di (lib??react/17.0.2/umd/react.production.min.js,react-dom/17.0.2/umd/react-dom.production.min.js,prop-types/15.8.1/prop-types.js:199:305)
    at Nj (lib??react/17.0.2/umd/react.production.min.js,react-dom/17.0.2/umd/react-dom.production.min.js,prop-types/15.8.1/prop-types.js:199:236)
    at sc (lib??react/17.0.2/umd/react.production.min.js,react-dom/17.0.2/umd/react-dom.production.min.js,prop-types/15.8.1/prop-types.js:199:96)
    at gf (lib??react/17.0.2/umd/react.production.min.js,react-dom/17.0.2/umd/react-dom.production.min.js,prop-types/15.8.1/prop-types.js:193:109)
```

**Comment by lakerswgq** [comment]
对于 imutable 数据源，传给组件的时候要转换成正常 js 对象
